### ISSUE TITLE
Darkvision not honored

### ISSUE THREAD

**Issue by agrtga** [schultzcole/FVTT-Wall-Height#7] opened 2020-07-12 19:27 UTC
Darkvision is not honored when this module is activated. Darkvision is restored immediately when the module is deactivated.

![Wall Height-Darkvision](https://user-images.githubusercontent.com/12749451/87254884-1feacd00-c454-11ea-9980-8b263cc75bc2.jpg)

**Comment by schultzcole** [comment] 2020-07-12 22:17
Thank you for the report. I am not able to reproduce the issue, however. Do you have other modules which may be conflicting, such as Haste, or possibly Darker Vision?

**Comment by agrtga** [comment] 2020-07-12 22:23
I have other mods, but none that appear to modify vision features. Here's a list:

- Ambient Doors
- Combat Enhancements
- Combat Utility Belt
- Dice So Nice!
- Follow Me!
- GM Notes
- Look at That
- Permission Viewer

**Comment by schultzcole** [comment] 2020-07-13 23:06
Sorry for the delay in getting back to you on this. Can you try it out in a brand new fresh world with only Wall Height enabled? If it still happens in that new world, could you export the scene that it is happening in and send it to me so I can try to diagnose the issue?

**Comment by agrtga** [comment] 2020-07-13 23:58
It's no problem, a day turnaround is a lot better than most.
I created a new test world and enabled only the Wall Height module. The problem is reproduced.

![Wall-Height problem](https://user-images.githubusercontent.com/12749451/87364813-9e259d00-c542-11ea-85b8-c7f90e321235.jpg)

`{
  "_id": "IBMK8sozoGAAV3QY",
  "name": "Scene",
  "sort": 100001,
  "flags": {
    "exportSource": {
      "world": "test_wall-height",
      "system": "D35E",
      "coreVersion": "0.6.4",
      "systemVersion": 0.55
    }
  },
  "description": "",
  "navigation": true,
  "navOrder": 100001,
  "navName": "",
  "active": true,
  "initial": null,
  "img": "test.png",
  "thumb": "worlds/test_wall-height/scenes/thumbs/IBMK8sozoGAAV3QY.png",
  "width": 2186,
  "height": 1573,
  "backgroundColor": "#999999",
  "tiles": [],
  "gridType": 1,
  "grid": 100,
  "shiftX": 0,
  "shiftY": 0,
  "gridColor": "#000000",
  "gridAlpha": 0.2,
  "gridDistance": 5,
  "gridUnits": "ft",
  "tokens": [
    {
      "_id": "l13kSd2L8MSP2NsX",
      "flags": {},
      "name": "Test PC",
      "displayName": 30,
      "img": "systems/D35E/icons/bestiary/vermin_giant_wasp_flying.png",
      "tint": null,
      "width": 1,
      "height": 1,
      "scale": 1,
      "mirrorX": false,
      "mirrorY": false,
      "x": 1100,
      "y": 900,
      "elevation": 4,
      "lockRotation": false,
      "rotation": -90,
      "effects": [],
      "vision": true,
      "dimSight": 0,
      "brightSight": 0,
      "dimLight": 0,
      "brightLight": 0,
      "sightAngle": 360,
      "lightAngle": 360,
      "lightColor": "",
      "lightAlpha": 1,
      "hidden": false,
      "actorId": "wkvLpJjH4GkZgRL3",
      "actorLink": true,
      "actorData": {},
      "disposition": 1,
      "displayBars": 0,
      "bar1": {
        "attribute": ""
      },
      "bar2": {
        "attribute": ""
      },
      "darkvision": 60,
      "visionLL": false,
      "locked": false
    }
  ],
  "walls": [
    {
      "_id": "B0DZuE5oQgXJjYdj",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 5,
          "wallHeightBottom": null
        }
      },
      "c": [
        1287,
        637,
        1287,
        1512
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "Bc3VR0o96hjfPs2C",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 5,
          "wallHeightBottom": null
        }
      },
      "c": [
        1287,
        1512,
        1450,
        1512
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "fJDgbAqbresRWyzs",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 5,
          "wallHeightBottom": null
        }
      },
      "c": [
        1450,
        1512,
        1450,
        637
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "gJRZkpowmVPYeHwK",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 5,
          "wallHeightBottom": null
        }
      },
      "c": [
        1450,
        637,
        1287,
        637
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "ScWTIySeL89vJz1k",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 10,
          "wallHeightBottom": null
        }
      },
      "c": [
        1500,
        525,
        1500,
        1200
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "cQFw24Pi129MrPPw",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 10,
          "wallHeightBottom": null
        }
      },
      "c": [
        1500,
        1200,
        1662,
        1200
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "SZMPLwZgEdpuuHOX",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 10,
          "wallHeightBottom": null
        }
      },
      "c": [
        1662,
        1200,
        1662,
        525
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    },
    {
      "_id": "m9EI8QZ0fgSe5EO2",
      "flags": {
        "wallHeight": {
          "wallHeightTop": 10,
          "wallHeightBottom": null
        }
      },
      "c": [
        1662,
        525,
        1500,
        525
      ],
      "move": 1,
      "sense": 2,
      "door": 0,
      "ds": 0,
      "dir": 0
    }
  ],
  "tokenVision": true,
  "fogExploration": true,
  "lights": [
    {
      "_id": "81Nf5VnSnB7dkRt5",
      "flags": {},
      "t": "l",
      "x": 1850,
      "y": 800,
      "rotation": 0,
      "dim": 16.9,
      "bright": 8.45,
      "angle": 360,
      "tintAlpha": 0.5,
      "darknessThreshold": 0,
      "locked": false
    }
  ],
  "globalLight": false,
  "darkness": 0,
  "playlist": "",
  "sounds": [],
  "templates": [],
  "journal": "",
  "notes": [],
  "weather": "",
  "drawings": []
}`

**Comment by schultzcole** [comment] 2020-07-14 00:09
Ah, I think I understand the issue now. The D35E system (and probably pf1 and pf2e as well) override some of the same methods that Wall Height does, creating a conflict. I think I can add specific compatibility for these systems. At least I hope it is simple enough...

**Comment by agrtga** [comment] 2020-07-14 00:11
That would be awesome. Your module really adds to the capability of the dynamic lighting.

**Comment by schultzcole** [comment] 2020-07-14 00:50
This issue should be resolved in 1.0.2. I did some cursory testing and it seems to work correctly, but I may have missed something because I'm not familiar with what is added by the D35E and pf1 systems.

I am going to close this issue, but feel free to re-open it if it seems like I missed something.

**Closed as completed by schultzcole** 2020-07-14 00:50 UTC
Labels: bug

**Comment by agrtga** [comment] 2020-07-14 01:05
It looks like you solved it! Thank you, amazingly fast turnaround.

![wall-height after 102](https://user-images.githubusercontent.com/12749451/87368772-9834b980-c54c-11ea-904c-0db7afa355a3.jpg)
