### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by capoeria** [schultzcole/FVTT-Wall-Height#12] opened 2020-12-14 18:22 UTC
How can I use the module? I dont see the height settings in the wall configuration dialog...

**Comment by schultzcole** [comment] 2020-12-14 22:16
If the height settings are not showing in the wall config, that must be some sort of bug or error. Can you check the console when you open the wall config dialog and see if any errors show up? (press F12 or CMD+SHIFT+I to open the console)

**Comment by capoeria** [comment] 2020-12-15 07:54
![Sin título](https://user-images.githubusercontent.com/74628021/102186562-1823ce80-3eb3-11eb-9c65-e02f06887d4a.png)

**Comment by schultzcole** [comment] 2020-12-15 19:51
Hmm, it looks like there are a lot of errors happening, probably further up in the logs. You also appear to have quite a few other modules installed. Can you reproduce this issue with *only* wall height active? If it only happens with other modules active, please try to identify which modules cause the conflict.

**Comment by capoeria** [comment] 2020-12-15 20:40
https://www.loom.com/share/d2bccf26c35443568a2da35cc2285f50

**Comment by schultzcole** [comment] 2020-12-16 20:27
Thanks for the video, that made the issue very clear. This issue should be fixed in 3.0.1 which will be out shortly!

**Closed as completed** 2020-12-16 20:26 UTC
Labels: bug
